import logging
from datetime import datetime, date
from services.upstox_client import UpstoxService
from services.instrument_mapper import InstrumentMapper
from database.connection import get_db
from database.collections import get_active_watchlist, save_watchlist, get_oi_baseline
from scorers.oi_scorer import OIScorer
from scorers.rs_scorer import RSScorer
from scorers.market_scorer import MarketScorer
from config.universe import SECTOR_INDEX_MAP, INDEX_KEYS

logger = logging.getLogger(__name__)

class PreMarketAnalyzer:
    def __init__(self):
        self.upstox = UpstoxService()
        self.mapper = InstrumentMapper()
        self.db = get_db()
        self.oi_scorer = OIScorer()
        self.rs_scorer = RSScorer()
        self.market_scorer = MarketScorer()
        
    def run(self):
        """Pre-market / Initial Pulse Analysis. Run at 9:31 AM IST."""
        logger.info("Starting Pre-Market Analyzer at 9:31 AM (Initial Conviction Pulse)...")
        
        # 1. Fetch Watchlist generated by EOD Scanner
        watchlist = get_active_watchlist()
        if not watchlist:
            logger.warning("No active watchlist found for today. Run EOD scanner first.")
            return
            
        symbols = [item['symbol'] for item in watchlist]
        logger.info(f"Loaded {len(symbols)} stocks from watchlist.")
        
        # 2. Map instruments
        instrument_keys = []
        symbol_to_key = {}
        for sym in symbols:
            key = self.mapper.get_equity_key(sym) or f"NSE_EQ|{sym}"
            instrument_keys.append(key)
            symbol_to_key[sym] = key
            
        # Add index keys for Nifty and VIX
        nifty_key = INDEX_KEYS.get("NIFTY 50", "NSE_INDEX|Nifty 50")
        vix_key = INDEX_KEYS.get("INDIA VIX", "NSE_INDEX|India VIX")
        all_keys = instrument_keys + [nifty_key, vix_key]
        
        # Also add sector keys
        sectors_needed = set()
        for sym in symbols:
            info = SECTOR_INDEX_MAP.get(sym, {})
            s_key = info.get('upstox_index_key')
            if s_key:
                sectors_needed.add(s_key)
        all_keys.extend(list(sectors_needed))

        # 3. Fetch Market Quotes
        try:
            quotes = self.upstox.get_market_quote(all_keys)
        except Exception as e:
            logger.error(f"Upstox API Quotes failed: {e}")
            return

        nifty_quote = quotes.get(nifty_key, {})
        vix_quote = quotes.get(vix_key, {})
        
        nifty_change = nifty_quote.get('change_pct', 0.0)
        vix_ltp = vix_quote.get('ltp', 15.0)

        # 4. Score each stock
        for sym in symbols:
            key = symbol_to_key[sym]
            stock_quote = quotes.get(key, {})
            stock_change = stock_quote.get('change_pct', 0.0)
            ltp = stock_quote.get('ltp', 100.0)
            
            # Auto-Skip: Gap Filter
            auto_skip = False
            status = 'active'
            skip_reason = ""
            
            if stock_change > 2.0:
                auto_skip = True
                skip_reason = "Gap Up > 2% (Exhaustion)"
            elif stock_change < -1.0:
                auto_skip = True
                skip_reason = "Gap Down (Against momentum)"
                
            # Fetch Option Chain
            try:
                expiries = self.upstox.get_expiry_dates(key)
                if expiries:
                    current_chain = self.upstox.get_option_chain(key, expiries[0])
                else:
                    raise ValueError("No expiry")
            except Exception as e:
                logger.error(f"[{sym}] Option chain failed: {e}")
                continue

            # Calculate fresh PCR
            total_ce = sum(c['call_oi'] for c in current_chain)
            total_pe = sum(c['put_oi'] for c in current_chain)
            current_pcr = total_pe / total_ce if total_ce > 0 else 1.0

            # Get Baseline
            baseline = get_oi_baseline(sym)
            if not baseline:
                logger.warning(f"[{sym}] No OI baseline found. Skipping OI Score.")
                baseline_pcr = 1.0
            else:
                baseline_pcr = baseline[0].get('pcr', 1.0) # Assuming uniform PCR stored
                
            # 5. Run Scorers
            # OI Score
            oi_data = {
                "current_option_chain": current_chain,
                "baseline_option_chain": baseline,
                "current_pcr": current_pcr,
                "baseline_pcr": baseline_pcr,
                "current_price": ltp
            }
            oi_res = self.oi_scorer.calculate(sym, oi_data)
            
            # If OI Scorer says auto skip (e.g. Put Buying detected)
            if oi_res.auto_skip:
                auto_skip = True
                skip_reason += f" | {oi_res.skip_reason}"
                
            # RS Score
            info = SECTOR_INDEX_MAP.get(sym, {})
            s_key = info.get('upstox_index_key')
            sector_change = 0.0
            if s_key and s_key in quotes:
                sector_change = quotes[s_key].get('change_pct', 0.0)
                
            rs_data = {
                "stock_change_pct": stock_change,
                "sector_index_change_pct": sector_change,
                "nifty_change_pct": nifty_change
            }
            rs_res = self.rs_scorer.calculate(sym, rs_data)
            
            # Market Score
            market_data = {
                "nifty_change_pct": nifty_change,
                "vix_value": vix_ltp,
                "index_pcr_rising": True # Simplification for mock
            }
            market_res = self.market_scorer.calculate("NIFTY", market_data)
            
            if auto_skip:
                status = 'skip'
                
            # Save results
            score_data = {
                'symbol': sym,
                'date': date.today().isoformat(),
                'status': status,
                'skip_reason': skip_reason.strip(" | "),
                'pre_market_oi_score': oi_res.score,
                'pre_market_rs_score': rs_res.score,
                'pre_market_market_score': market_res.score,
                'ltp': ltp,
                'change_pct': stock_change
            }
            save_watchlist(score_data)
            logger.info(f"[{sym}] Pre-Market updated. Status: {status}, OI: {oi_res.score}, RS: {rs_res.score}")
            
        logger.info("Pre-Market Analyzer complete.")
